FROM mhart/alpine-node:8

ARG env

RUN echo http://mirror.yandex.ru/mirrors/alpine/v3.5/main > /etc/apk/repositories; \
    echo http://mirror.yandex.ru/mirrors/alpine/v3.5/community >> /etc/apk/repositories

RUN apk update
RUN apk add --no-cache
RUN apk add git

WORKDIR /enterprise

COPY ./ /enterprise/

RUN npm config set registry https://registry.npm.taobao.org
RUN npm config set unsafe-perm true
RUN npm install -g yarn
RUN yarn global add pm2
RUN yarn install

EXPOSE 3000

CMD ["/bin/bash"]